const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:"chrome"});
 const page=await browser.newPage({viewport:{width:1300,height:1000},serviceWorkers:'block'});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('https://**/*',r=>r.abort());
 await page.goto('http://localhost:4173');
 assert.equal(await page.locator('.leaflet-container').count(),1);
 assert.equal(await page.locator('#route-from option').count(),10);
 assert.equal(await page.locator('#route-variant').inputValue(),'detour');
 await page.click('#test-cycle-route');
 await page.waitForFunction(()=>document.querySelector('#route-status').textContent.includes('5.0 km mapped'));
 assert.ok((await page.locator('#route-status').innerText()).includes('not a continuous navigation route'));
 assert.equal(await page.locator('.leaflet-overlay-pane path').count(),35);
 await page.selectOption('#route-from','frankton');await page.selectOption('#route-to','queenstown');await page.click('#test-cycle-route');
 await page.waitForFunction(()=>document.querySelector('#route-status').textContent.startsWith('Frankton roadside path'));
 await page.selectOption('#route-from','queenstown');await page.selectOption('#route-to','frankton');
 await page.selectOption('#route-variant','normal');
 assert.equal(await page.locator('.leaflet-overlay-pane path').count(),0);
 await page.click('#test-cycle-route');
 await page.waitForFunction(()=>document.querySelector('#route-status').textContent.includes('5.9 km'));
 assert.ok((await page.locator('#route-status').innerText()).includes('closed'));
 assert.equal(await page.locator('.leaflet-overlay-pane path').count(),18);
 await page.selectOption('#route-from','frankton');await page.selectOption('#route-to','queenstown');await page.click('#test-cycle-route');
 await page.waitForFunction(()=>document.querySelector('#route-status').textContent.startsWith('Frankton Beach →'));
 await page.selectOption('#route-to','arrowtown');await page.click('#test-cycle-route');assert.ok((await page.locator('#route-status').innerText()).includes('Only Queenstown'));
 assert.equal(await page.locator('.leaflet-overlay-pane path').count(),0);
 await page.selectOption('#route-from','queenstown');await page.selectOption('#route-to','frankton');
 await page.route('**/data/queenstown-frankton.v1.json',r=>r.fulfill({status:500,body:'failed'}));
 await page.click('#test-cycle-route');await page.waitForFunction(()=>document.querySelector('#route-status').textContent.startsWith('Cycle route unavailable'));
 await page.click('#reset');assert.equal(await page.locator('.leaflet-container').count(),1);
 await page.unroute('**/data/queenstown-frankton.v1.json');
 await page.route('**/data/queenstown-frankton.v1.json',async r=>{await new Promise(resolve=>setTimeout(resolve,500));await r.continue();});
 await page.click('#test-cycle-route');await page.selectOption('#route-to','arrowtown');await page.waitForTimeout(700);
 assert.equal(await page.locator('.leaflet-overlay-pane path').count(),0);
 await page.unroute('**/data/queenstown-frankton.v1.json');
 await page.route('**/routing/frankton.js*',r=>r.abort());await page.reload();
 assert.equal(await page.locator('.leaflet-container').count(),1);
 await page.click('#test-cycle-route');await page.waitForFunction(()=>document.querySelector('#route-status').textContent.startsWith('Cycle route unavailable'));
 await page.unroute('**/routing/frankton.js*');await page.reload();
 await page.route('**/data/queenstown-frankton-detour.v1.json',r=>r.fulfill({status:200,contentType:'application/json',body:'{}'}));
 await page.click('#test-cycle-route');await page.waitForFunction(()=>document.querySelector('#route-status').textContent.startsWith('Cycle route unavailable'));
 assert.equal(await page.locator('.leaflet-overlay-pane path').count(),0);
 assert.equal(await page.locator('.leaflet-container').count(),1);
 assert.deepEqual(errors,[]);
 console.log('Browser checks passed: startup, both directions, unsupported pair, HTTP failure, stale response, module failure.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
