const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async () => {
 const browser = await chromium.launch({ headless: true, channel: 'chrome' });
 const page = await browser.newPage({ viewport: { width: 1280, height: 1000 }, serviceWorkers: 'block' });
 const errors = []; page.on('pageerror', e => errors.push(e.message));
 const cell = (count, extra = {}) => ({ origin: 'fernhill', destination: 'frankton', modes: '["bike","bus"]', timeBand: 'weekday-am', changeReason: 'safer-cycle-route', count, ...extra });
 const data = { ok: true, minimumGroupSize: 5, totalSubmissions: 24, cells: [cell(5), cell(8, { destination: 'queenstown' }), cell(7, { origin: 'arrowtown', modes: '["car"]' }), cell(4)] };
 await page.route('**/api/commutes/summary', r => r.fulfill({ json: data }));
 await page.goto('http://localhost:4173/insights.html');
 await page.waitForFunction(() => document.querySelector('#visible-responses').textContent === '20');
 assert.equal(await page.locator('.flow-line').count(), 3);
 assert.match(await page.locator('#origins-content').innerText(), /Fernhill\s+13/);
 await page.selectOption('#filter-mode', 'bus');
 assert.equal(await page.locator('#visible-responses').innerText(), '13');
 const downloadPromise = page.waitForEvent('download'); await page.click('#export-csv');
 const download = await downloadPromise;
 const stream = await download.createReadStream(); const chunks = []; for await (const c of stream) chunks.push(c);
 const csv = Buffer.concat(chunks).toString(); assert.equal(csv.split('\n').length, 3); assert.ok(!csv.includes('Arrowtown'));
 await page.selectOption('#filter-mode', 'ferry');
 assert.equal(await page.locator('#export-csv').isDisabled(), true);
 assert.match(await page.locator('#overview-status').innerText(), /No publishable/);
 await page.click('#clear-filters');
 await page.screenshot({ path: '../insights-desktop.png', fullPage: true });
 await page.setViewportSize({ width: 390, height: 844 });
 assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
 await page.screenshot({ path: '../insights-mobile.png', fullPage: true });
 await page.unroute('**/api/commutes/summary');
 await page.route('**/api/commutes/summary', r => r.fulfill({ status: 503, json: { ok: false } }));
 await page.reload(); await page.waitForFunction(() => document.querySelector('#overview-status').textContent.includes('unavailable'));
 assert.equal(await page.locator('#export-csv').isDisabled(), true);
 await page.click('text=Back to map'); assert.equal(await page.locator('.leaflet-container').count(), 1);
 assert.deepEqual(errors, []);
 await browser.close(); console.log('Insights browser checks passed: summaries, filters, CSV, empty/error states, mobile and map isolation.');
})().catch(e => { console.error(e); process.exit(1); });
